project:
  type: website
  output-dir: docs

website:
  title: "Samuel M. Hickey"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Research.qmd
        text: Research
      - href: https://jkbirnir.github.io/GVPT729B/
        text: GVPT729
      - about.qmd

format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

